#!/bin/bash

source /etc/sysconfig/network-scripts/ifcfg-$1
source /etc/128technology/plugins/network-scripts/common/namespace_helpers

KNI_NAME=$1
KNI_GW=${6#"--kni-gateway="}
NS=$2
NS_NAME=$(namespace_get_name $NS)
ENDPOINT=$(cat /etc/128technology/wireguard/$NS.conf | sed -n -e '/Endpoint/s/.*=//p' | sed 's/:.*//')

create_namespace $NS
add_interface_to_namespace $NS $KNI_NAME
namespace_interface_up $NS $KNI_NAME
namespace_execute $NS ip address add $IPADDR/$PREFIX dev $KNI_NAME
namespace_execute $NS ip route add $ENDPOINT via $KNI_GW
namespace_execute $NS sysctl -w net.ipv4.ip_forward=1 &>/dev/null

# check if running and if not restart tunnel service
namespace_execute $NS wg show $NS_NAME >&- 2>&- || systemctl start 128t-wireguard@$NS_NAME
