#!/bin/bash

source /etc/128technology/plugins/network-scripts/common/namespace_helpers

for arg in "$@"
do
case $arg in
  --namespace=*)
  NS="${arg#*=}"
  shift
  ;;
esac
done

NS_NAME=$(namespace_get_name $NS)

namespace_execute $NS wg show $NS_NAME >&- 2>&-
if [ $? -eq 0 ]; then
  echo "up"
else
  echo "down"
fi
